In [1]:
import pandas as pd
import numpy as np
import igraph as ig
pd.options.display.float_format = '{:,.2f}'.format
import pickle

In [54]:
usuarios=pd.read_csv('animelist.csv',
                     na_values=["Unknown"],
                     header=0,
                     usecols=[0,1,2,3],
                     names=["user_id","anime_id","rating" ,"watching_status"],
                     dtype={"user_id":str,"anime_id":str,"rating":np.float64,"watching_status":np.float64})

In [55]:
usuarios

          user_id anime_id  rating  watching_status
0               0       67    9.00             1.00
1               0     6702    7.00             1.00
2               0      242   10.00             1.00
3               0     4898    0.00             1.00
4               0       21   10.00             1.00
...           ...      ...     ...              ...
109224742  353404      507    7.00             2.00
109224743  353404      392    9.00             2.00
109224744  353404      882    6.00             2.00
109224745  353404      883    8.00             2.00
109224746  353404      149    0.00             6.00

[109224747 rows x 4 columns]

In [3]:
anime=pd.read_csv('anime.csv', dtype={'id':str})
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16214 entries, 0 to 16213
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        16214 non-null  object
 1   Name      16214 non-null  object
 2   Score     11091 non-null  float64
 3   Genres    16151 non-null  object
 4   Episodes  15737 non-null  float64
 5   Aired     4745 non-null   object
dtypes: float64(2), object(4)
memory usage: 760.2+ KB

,id,Name,Score,Genres,Episodes,Aired
0,32455,Gekidol,5.76,Music,12.00,Winter 2021
1,35252,Hatena☆Illusion,5.37,"Comedy, Supernatural, Romance, Ecchi",12.00,Winter 2020
2,36458,Soukou Musume Senki,5.30,"Action, Military, Fantasy",12.00,Winter 2021
3,37345,Plunderer,6.50,"Action, Ecchi, Fantasy, Shounen",24.00,Winter 2020
4,37522,Pet,6.48,"Mystery, Psychological, Supernatural, Seinen",13.00,Winter 2020
...,...,...,...,...,...,...
200,43325,Yuukoku no Moriarty 2nd Season,NaN,"Mystery, Historical, Psychological, Shounen",13.00,Spring 2021
201,43350,Gebäude Bäude,6.33,"Sci-Fi, Comedy",10.00,Fall 2020
202,43729,Semi wa Magic Cube 2nd Season,NaN,"Action, Fantasy",26.00,Spring 2020
203,45207,Okashi na Sabaku no Suna to Manu,NaN,Comedy,50.00,Winter 2021
204,46118,Wave!!: Surfing Yappe!! (TV),6.05,"Slice of Life, Sports",12.00,Winter 2021

In [4]:
anime['Genres'] = anime['Genres'].fillna('').astype(str) 
anime['Aired'] = anime['Aired'].fillna('').astype(str)# como hay NAS entonces el cuaderno de jupyter no lo lee

In [5]:
anime['Aired']

0        Spring 1998
1        Spring 2001
2        Spring 1978
3
4
            ...
16209
16210
16211    Spring 2011
16212
16213
Name: Aired, Length: 16214, dtype: object

In [6]:
anime = anime.query("Episodes > 9 & Aired.str.contains('202')").sort_values(by=["id"], ascending=True).reset_index(drop=True)

In [7]:
id=anime['id'].unique()
id

array(['32455', '35252', '36458', '37345', '37522', '37576', '37587',
       '37599', '37870', '37890', '37962', '37984', '38005', '38256',
       '38302', '38337', '38474', '38476', '38481', '38555', '38656',
       '38668', '38669', '38790', '38830', '38835', '38843', '38853',
       '38883', '38909', '38924', '39017', '39184', '39292', '39388',
       '39463', '39469', '39534', '39535', '39547', '39551', '39575',
       '39582', '39583', '39587', '39609', '39617', '39681', '39710',
       '39730', '39783', '39790', '39792', '39808', '39942', '39948',
       '39960', '39966', '39988', '39990', '40010', '40028', '40045',
       '40046', '40056', '40059', '40074', '40075', '40085', '40128',
       '40136', '40137', '40148', '40165', '40221', '40230', '40272',
       '40358', '40359', '40392', '40397', '40403', '40417', '40436',
       '40454', '40473', '40483', '40496', '40497', '40504', '40513',
       '40529', '40530', '40532', '40540', '40550', '40571', '40591',
       '40594', '40595', '40610', '40623', '40677', '40679', '40708',
       '40716', '40738', '40748', '40750', '40758', '40763', '40776',
       '40783', '40786', '40803', '40815', '40833', '40839', '40842',
       '40850', '40852', '40854', '40879', '40893', '40902', '40907',
       '40908', '40911', '40930', '40934', '40953', '40956', '40958',
       '40961', '40964', '40974', '40983', '40995', '41006', '41025',
       '41074', '41109', '41120', '41226', '41266', '41283', '41312',
       '41345', '41349', '41353', '41364', '41372', '41380', '41389',
       '41392', '41401', '41405', '41426', '41433', '41440', '41470',
       '41491', '41520', '41556', '41558', '41573', '41574', '41619',
       '41638', '41686', '41694', '41762', '41778', '41783', '41807',
       '41834', '41899', '41911', '41930', '42090', '42203', '42250',
       '42260', '42391', '42414', '42506', '42516', '42571', '42657',
       '42668', '42717', '42822', '42825', '42883', '42897', '42923',
       '42941', '42979', '43229', '43299', '43325', '43350', '43729',
       '45207', '46118'], dtype=object)

In [8]:
anime['Aired'].unique()

array(['Winter 2021', 'Winter 2020', 'Summer 2020', 'Fall 2020',
       'Spring 2020', 'Spring 2021'], dtype=object)

In [9]:
usuarios=(usuarios
 .query('anime_id in @id and watching_status==2')
.sort_values(by=["user_id", "anime_id"], ascending=[True, True]).reset_index(drop=True))

In [10]:
usuarios=usuarios.drop(['watching_status'], axis=1)

In [11]:
usuarios=usuarios.merge(anime,left_on="anime_id",right_on="id",how="left")

In [12]:
usuarios

,user_id,anime_id,rating,id,Name,Score,Genres,Episodes,Aired
0,1,38883,8.00,38883,Haikyuu!!: To the Top,8.39,"Comedy, Sports, Drama, School, Shounen",13.00,Winter 2020
1,1,39547,9.00,39547,Yahari Ore no Seishun Love Comedy wa Machigatt...,8.46,"Slice of Life, Comedy, Drama, Romance, School",12.00,Summer 2020
2,1,39587,9.00,39587,Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season,8.50,"Psychological, Drama, Thriller, Fantasy",13.00,Summer 2020
3,1,40221,8.00,40221,Kami no Tou,7.66,"Action, Adventure, Mystery, Drama, Fantasy",13.00,Spring 2020
4,1,40776,9.00,40776,Haikyuu!!: To the Top 2nd Season,8.57,"Comedy, Sports, Drama, School, Shounen",12.00,Fall 2020
...,...,...,...,...,...,...,...,...,...
1052155,99997,40839,7.00,40839,"Kanojo, Okarishimasu",7.37,"Comedy, Romance, School, Shounen",12.00,Summer 2020
1052156,99997,40902,8.00,40902,Shokugeki no Souma: Gou no Sara,7.35,"Ecchi, School, Shounen",13.00,Spring 2020
1052157,99997,41226,5.00,41226,Uzaki-chan wa Asobitai!,7.05,"Slice of Life, Comedy, Romance, Ecchi",12.00,Summer 2020
1052158,99997,41345,6.00,41345,Noblesse,6.83,"Action, Supernatural, Vampire, School",13.00,Fall 2020
1052159,99997,41353,7.00,41353,The God of High School,7.07,"Action, Sci-Fi, Adventure, Comedy, Supernatura...",13.00,Summer 2020

In [13]:
USERS = pd.DataFrame((usuarios['user_id'].unique(),  # Obtener valores únicos de la primera columna
                  range(len(usuarios['user_id'].unique()))),  # Generar identificadores únicos
                 index=['user', 'Identificador']).T  # Transponer para obtener un DataFrame

# Creación del DataFrame para la segunda columna (C)
ANIMES = pd.DataFrame((usuarios['anime_id'].unique(),  # Obtener valores únicos de la segunda columna
                  (np.full(len(usuarios['anime_id'].unique()), len(usuarios['user_id'].unique())) + range(len(usuarios['anime_id'].unique())))),  # Generar identificadores únicos
                      #ya hay identificadores unicos para todos los usuarios
                      # toca generar identificadores unicos para todos los animes
                 index=['anime', 'Identificador']).T  # Transponer para obtener un DataFrame

In [52]:
USERS

          user Identificador
0            1             0
1        10000             1
2       100003             2
3       100004             3
4       100006             4
...        ...           ...
111194   99988        111194
111195   99989        111195
111196   99990        111196
111197   99994        111197
111198   99997        111198

[111199 rows x 2 columns]

In [15]:
Indentificados=usuarios.merge(USERS,left_on='user_id',right_on="user",how="left").merge(ANIMES,left_on='anime_id',right_on="anime",how="left")
Indentificados

,user_id,anime_id,rating,id,Name,Score,Genres,Episodes,Aired,user,Identificador_x,anime,Identificador_y
0,1,38883,8.00,38883,Haikyuu!!: To the Top,8.39,"Comedy, Sports, Drama, School, Shounen",13.00,Winter 2020,1,0,38883,111199
1,1,39547,9.00,39547,Yahari Ore no Seishun Love Comedy wa Machigatt...,8.46,"Slice of Life, Comedy, Drama, Romance, School",12.00,Summer 2020,1,0,39547,111200
2,1,39587,9.00,39587,Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season,8.50,"Psychological, Drama, Thriller, Fantasy",13.00,Summer 2020,1,0,39587,111201
3,1,40221,8.00,40221,Kami no Tou,7.66,"Action, Adventure, Mystery, Drama, Fantasy",13.00,Spring 2020,1,0,40221,111202
4,1,40776,9.00,40776,Haikyuu!!: To the Top 2nd Season,8.57,"Comedy, Sports, Drama, School, Shounen",12.00,Fall 2020,1,0,40776,111203
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052155,99997,40839,7.00,40839,"Kanojo, Okarishimasu",7.37,"Comedy, Romance, School, Shounen",12.00,Summer 2020,99997,111198,40839,111233
1052156,99997,40902,8.00,40902,Shokugeki no Souma: Gou no Sara,7.35,"Ecchi, School, Shounen",13.00,Spring 2020,99997,111198,40902,111204
1052157,99997,41226,5.00,41226,Uzaki-chan wa Asobitai!,7.05,"Slice of Life, Comedy, Romance, Ecchi",12.00,Summer 2020,99997,111198,41226,111231
1052158,99997,41345,6.00,41345,Noblesse,6.83,"Action, Supernatural, Vampire, School",13.00,Fall 2020,99997,111198,41345,111275
1052159,99997,41353,7.00,41353,The God of High School,7.07,"Action, Sci-Fi, Adventure, Comedy, Supernatura...",13.00,Summer 2020,99997,111198,41353,111206

In [16]:
Aristas=Indentificados[['Identificador_x', 'Identificador_y']]
Aristas

        Identificador_x Identificador_y
0                     0          111199
1                     0          111200
2                     0          111201
3                     0          111202
4                     0          111203
...                 ...             ...
1052155          111198          111233
1052156          111198          111204
1052157          111198          111231
1052158          111198          111275
1052159          111198          111206

[1052160 rows x 2 columns]

In [17]:
type=np.concatenate((np.full(len(usuarios['user_id'].unique()), True), np.full(len(usuarios['anime_id'].unique()), False)))

In [18]:
name=np.concatenate((usuarios['user_id'].unique(),usuarios['anime_id'].unique()))

In [19]:
# Assuming Aristas is your DataFrame
Aristas['Identificador_x'] = Aristas['Identificador_x'].astype(int)
Aristas['Identificador_y'] = Aristas['Identificador_y'].astype(int)

C:\Users\Pc\AppData\Local\Temp\ipykernel_1116\1100820221.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Aristas['Identificador_x'] = Aristas['Identificador_x'].astype(int)
C:\Users\Pc\AppData\Local\Temp\ipykernel_1116\1100820221.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Aristas['Identificador_y'] = Aristas['Identificador_y'].astype(int)

In [20]:
g = ig.Graph.DataFrame(Aristas, directed=False) 
g.vs['type']=type # para volverlo bipartita
g.vs['name']=name

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 ...]

In [27]:
g_anime= g.bipartite_projection(which=0) # para obtener Y'Y YY'

# AHORA SE PUEDE JUGAR CON LA BASE

In [3]:
# Cargar el objeto desde el archivo PKL
with open("g_anime.pkl", "rb") as archivo:
    g_anime_recuperado = pickle.load(archivo)
print("Objeto cargado correctamente desde")

Objeto cargado correctamente desde

In [9]:
#print(g_anime_recuperado)
g_anime = g_anime_recuperado

In [10]:
ig.summary(g_anime)

IGRAPH UNWT 177 12313 --
+ attr: name (v), type (v), weight (e)

In [11]:
grafico=ig.plot(g_anime)
grafico.save("grafico.png")
# adaptado de

In [43]:
sorted(g_anime.closeness())

[0.4985835694050991,
 0.504297994269341,
 0.5101449275362319,
 0.5191740412979351,
 0.5207100591715976,
 0.5253731343283582,
 0.5285285285285285,
 0.5317220543806647,
 0.5349544072948328,
 0.5382262996941896,
 0.55,
 0.5517241379310345,
 0.5517241379310345,
 0.584717607973422,
 0.584717607973422,
 0.584717607973422,
 0.584717607973422,
 0.584717607973422,
 0.584717607973422,
 0.584717607973422,
 0.5986394557823129,
 0.6111111111111112,
 0.6175438596491228,
 0.6219081272084805,
 0.6423357664233577,
 0.8186046511627907,
 0.8262910798122066,
 0.8262910798122066,
 0.8461538461538461,
 0.8461538461538461,
 0.8543689320388349,
 0.8543689320388349,
 0.8543689320388349,
 0.8543689320388349,
 0.8543689320388349,
 0.8543689320388349,
 0.8585365853658536,
 0.8585365853658536,
 0.8627450980392157,
 0.8627450980392157,
 0.8627450980392157,
 0.8627450980392157,
 0.8712871287128713,
 0.8712871287128713,
 0.8712871287128713,
 0.8712871287128713,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.8756218905472637,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.88,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8844221105527639,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8934010152284264,
 0.8979591836734694,
 0.8979591836734694,
 0.8979591836734694,
 0.8979591836734694,
 0.8979591836734694,
 0.8979591836734694,
 0.9025641025641026,
 0.9025641025641026,
 0.9072164948453608,
 0.9166666666666666,
 0.9166666666666666,
 0.9166666666666666,
 0.9214659685863874,
 0.9214659685863874,
 0.9214659685863874,
 0.9263157894736842,
 0.9263157894736842,
 0.9263157894736842,
 0.9263157894736842,
 0.9263157894736842,
 0.9312169312169312,
 0.9312169312169312,
 0.9312169312169312,
 0.9312169312169312,
 0.9312169312169312,
 0.9312169312169312,
 0.9312169312169312,
 0.9361702127659575,
 0.9361702127659575,
 0.9411764705882353,
 0.9411764705882353,
 0.9411764705882353,
 0.9411764705882353,
 0.946236559139785,
 0.946236559139785,
 0.946236559139785,
 0.946236559139785,
 0.946236559139785,
 0.946236559139785,
 0.946236559139785,
 0.9513513513513514,
 0.9513513513513514,
 0.9513513513513514,
 0.9513513513513514,
 0.9565217391304348,
 0.9617486338797814,
 0.9617486338797814,
 0.9617486338797814,
 0.9617486338797814,
 0.9617486338797814,
 0.967032967032967,
 0.967032967032967,
 0.9723756906077348,
 0.9777777777777777,
 0.9832402234636871,
 0.9832402234636871]